<?php namespace App\Validation;

use Exception;
use Illuminate\Support\MessageBag;

class ValidationException extends \Exception
{

    /**
     * @var MessageBag
     */
    private $errors;

    public function __construct(MessageBag $errors, $message = "", $code = 0, Exception $previous = null)
    {
        parent::__construct($message, $code, $previous); // TODO: Change the autogenerated stub
        $this->errors = $errors;
    }

    /**
     * @return MessageBag
     */
    public function errors()
    {
        return $this->errors;
    }


} 